# Lade Parameter der Simulation
library(viridis)
plotColor <- magma(12,begin = 0)
plotColor2 <- cividis(12,begin = 0)
plotColor3 <- viridis(12,begin = 0)

# Aus Distribution Comparison Plot
#"NB" plotColor3[5] 
#"PIG" plotColor[5]
#"PB: c = 10 E" plotColor3[8]
#"PB: c = 1000 E" plotColor3[10]
#"DEL: nu = 0.1" plotColor2[9]
#"DEL: nu = 0.9"plotColor2[12]

# von vorher:
# Pois: rgb(003e6eff) rgb( 0, 62, 110, maxColorValue= 255)
# NB: rgb( 116, 149, 152, maxColorValue= 255)

col_def <- c( "pois"= rgb( 0, 62, 110, maxColorValue= 255),"pb"= plotColor3[10], "nb"=  rgb( 116, 149, 152, maxColorValue= 255), "del" = plotColor2[9] , "pig" = plotColor[5])




# Symbols and thickness:

symb_def <- c("pois"= 19, "pb"=  3, "nb"= 17,  "del" = 15, "pig" = 4)

def_lwd = c("pois"=0,"pb"= 2, "nb"=0,"del" =0,"pig" = 2)

load("GenData/Parameter_BasicSwitchBurst.rda")
load("GenData/Parameter_BasicBurst_BasicBurst_IG.rda")

########################################################################################################################################
# Basic Modell Fits: Zusammenfassung


BIC_basic_pois<- c(NA,1000)
BIC_basic_nb<- c(NA,1000)
BIC_basic_pb<- c(NA,1000)
BIC_basic_del<- c(NA,1000)
BIC_basic_pig<- c(NA,1000)

for(i in 1:1000){

    load(file=paste0("FitData/Basic/basic_",i,".rda"))


    BIC_basic_pois[i] <- f_pois$BIC
    BIC_basic_nb[i] <- f_nb$BIC
    BIC_basic_pb[i] <- f_pb$BIC
    BIC_basic_pig[i] <- f_pig$BIC
    BIC_basic_del[i] <- f_del$BIC
    }


# GOF
BIC_basic_help <- matrix(rep(0,1000), ncol = 1)
rownames( BIC_basic_help) <- 1:1000
p_x2_basic <- rep(NA,1000)

for(i in c(1:228,230:1000)){
    load(file=paste0("GOFData/Basic/p_gof_basic_",i,".rda"))
    BIC_basic_help[i,] <- minBIC
    rownames( BIC_basic_help)[i] <- names(minBIC)
    p_x2_basic[i] <- p_x2$p.value
}

p_x2_basic[229] <- 0

#help <- 

#help <- factor(rownames( BIC_basic_help), labels=c("pois" = 1, "nb" = 3, "pig" = 5,  "229" = 100))
#levels(help)[levels(help)=="pig"] <- 5
#levels(help)[levels(help)=="del"] <- 4
#levels(help)[levels(help)=="nb"] <- 3
#levels(help)[levels(help)=="pb"] <- 2
#levels(help)[levels(help)=="pois"] <- 1

BIC_basic <- rownames( BIC_basic_help)


#, labels=c("pois"=1, "pb" = 2, "nb" = 3, "del" = 4, "pig" = 5, "229" = 100), ordered = TRUE)

# true parameter
t_param_basic <-  c(Parameter_Basic$trans[i], Parameter_Basic$degr[i])

# derived "true" parameter of the PB
Parameter_Pois <- Parameter_Basic$trans/Parameter_Basic$degr



# Filterung mit GOF
pdf("GOFData/Basic/Analyse_Basic_2.pdf", width = 10, height = 4)
plot(Parameter_Pois[p_x2_basic[!is.na(p_x2_basic)] > 0.05], rep(0,length(Parameter_Pois[p_x2_basic[!is.na(p_x2_basic)] > 0.05])),
     bty ="n", yaxt = "n",ylim = c(-1,1),type = "p", pch = symb_def[BIC_basic[p_x2_basic[!is.na(p_x2_basic)] > 0.05]], lwd= def_lwd[BIC_basic[p_x2_basic[!is.na(p_x2_basic)] > 0.05]], 
     col = col_def[ BIC_basic[p_x2_basic[!is.na(p_x2_basic)] > 0.05]], xlab = bquote(paste("True ",lambda," of Pois")) ,ylab ="", main = "Data generated by basic model", cex = 1.2)
#legend("topright", legend = c("Pois", "PB", "NB", "DEL", "PIG"), col = col_def, pch = symb_def, bty ="n", cex = 1.2, lwd = def_lwd, lty = 0)
dev.off()



########################################################################################################################################
# Switch Modell Fits: Zusammenfassung

BIC_switch_pois<- c(0,1000)
BIC_switch_nb<- c(0,1000)
BIC_switch_pb<- c(0,1000)
BIC_switch_del<- c(0,1000)
BIC_switch_pig<- c(0,1000)

for(i in 1:1000){

    # fitted NB parameter
    load(file=paste0("FitData/Switch/switch_",i,".rda"))
    #f_param_pb <- f_pb$par

    BIC_switch_pois[i] <- f_pois$BIC
    BIC_switch_nb[i] <- f_nb$BIC
    BIC_switch_pb[i] <- f_pb$BIC
    BIC_switch_pig[i] <- f_pig$BIC
    BIC_switch_del[i] <- f_del$BIC

}

# GOF
BIC_switch_help <- matrix(rep(0,1000), ncol = 1)
rownames( BIC_switch_help) <- 1:1000
p_x2_switch <- rep(0,1000)

for(i in 1:1000){
    load(file=paste0("GOFData/Switch/p_gof_switch_",i,".rda"))
    BIC_switch_help[i,] <- minBIC
    rownames( BIC_switch_help)[i] <- names(minBIC)
    p_x2_switch[i] <- p_x2$p.value
}



BIC_switch <-  rownames( BIC_switch_help)


# true parameter
t_param_switch <-  c(Parameter_Switch$act[i], Parameter_Switch$deact[i], Parameter_Switch$on[i], Parameter_Switch$degr[i])

# derived "true" parameter of the PB
Parameter_PB_alpha <- Parameter_Switch$act/Parameter_Switch$degr
Parameter_PB_beta <- Parameter_Switch$deact/Parameter_Switch$degr
Parameter_PB_c <- Parameter_Switch$on/Parameter_Switch$degr



# Filterung mit GOF
pdf("GOFData/Switch/Analyse_Switch_2_1.pdf", width = 10, height = 4)
plot(Parameter_PB_alpha[p_x2_switch > 0.05], Parameter_PB_beta[p_x2_switch > 0.05],xlim = c(0,70), bty = "n", type = "p", pch = symb_def[BIC_switch[p_x2_switch > 0.05]], col = col_def[BIC_switch[p_x2_switch > 0.05]] , xlab = bquote(paste("True ", alpha, " of PB")) , ylab = bquote(paste("True ", beta, " of PB")), cex = 1.2, main = "Data generated by switching model", 
     lwd= def_lwd[BIC_switch[p_x2_switch > 0.05]])
#legend("topright", legend = c("Pois", "PB", "NB", "DEL", "PIG"), col = col_def, pch = symb_def, bty ="n", cex = 1.2, lwd = def_lwd, lty = 0)
dev.off()

pdf("GOFData/Switch/Analyse_Switch_2_2.pdf", width = 10, height = 4)
plot(Parameter_PB_c[p_x2_switch > 0.05], Parameter_PB_beta[p_x2_switch > 0.05],xlim = c(0,2800), bty = "n", type = "p", pch = symb_def[BIC_switch[p_x2_switch > 0.05]], col = col_def[BIC_switch[p_x2_switch > 0.05] ], xlab = bquote(paste("True c of PB")), ylab =  bquote(paste("True ", beta, " of PB")), cex = 1.2, main = "", 
     lwd= def_lwd[BIC_switch[p_x2_switch > 0.05]])
#legend("topright", legend = c("Pois", "PB", "NB", "DEL", "PIG"), col = col_def, pch = symb_def, bty ="n", cex = 1.2, lwd = def_lwd, lty = 0)
dev.off()

pdf("GOFData/Switch/Analyse_Switch_2_3.pdf", width = 10, height = 4)
plot(Parameter_PB_alpha[p_x2_switch > 0.05], Parameter_PB_c[p_x2_switch > 0.05],xlim = c(0,70), bty = "n", type = "p", pch = symb_def[BIC_switch[p_x2_switch > 0.05]], col = col_def[BIC_switch[p_x2_switch > 0.05] ], xlab =  bquote(paste("True ", alpha, " of PB")), ylab =bquote(paste("True c of PB")), cex = 1.2, main = "",
     lwd= def_lwd[BIC_switch[p_x2_switch > 0.05]])
#legend("topright", legend = c("Pois", "PB", "NB", "DEL", "PIG"), col = col_def, pch = symb_def, bty ="n", cex = 1.2, lwd = def_lwd, lty = 0)
dev.off()


########################################################################################################################################
# Burst Modell Fits: Zusammenfassung

BIC_burst_pois<- c(0,1000)
BIC_burst_nb<- c(0,1000)
BIC_burst_pb<- c(0,1000)
BIC_burst_pig<- c(0,1000)
BIC_burst_del<- c(0,1000)

for(i in 1:1000){

    # fitted NB parameter
    load(file=paste0("FitData/Burst/burst_",i,".rda"))
    #f_param_nb <- f_nb$par

    BIC_burst_pois[i] <- f_pois$BIC
    BIC_burst_nb[i] <- f_nb$BIC
    BIC_burst_pb[i] <- f_pb$BIC
    BIC_burst_pig[i] <- f_pig$BIC
    BIC_burst_del[i] <- f_del$BIC
}

# GOF
BIC_burst_help <- matrix(rep(0,1000), ncol = 1)
rownames( BIC_burst_help) <- 1:1000
p_x2_burst <- rep(0,1000)

for(i in 1:1000){
    load(file=paste0("GOFData/Burst/p_gof_burst_",i,".rda"))
    BIC_burst_help[i,] <- minBIC
    rownames(BIC_burst_help)[i] <- names(minBIC)
    p_x2_burst[i] <- p_x2$p.value
}



BIC_burst <- rownames(BIC_burst_help)

# true parameter
t_param_burst <- c(Parameter_Burst$burst[i], Parameter_Burst$size[i], Parameter_Burst$degr[i])

# derived "true" parameter of the NB
Parameter_NB_r <- Parameter_Burst$burst/Parameter_Burst$degr
Parameter_NB_p <-  1/(Parameter_Burst$size+1)




# Filterung mit GOF
pdf("GOFData/Burst/Analyse_Burst_2.pdf", width = 10, height = 4)
plot(Parameter_NB_p[p_x2_burst > 0.05], Parameter_NB_r[p_x2_burst > 0.05], type = "p", bty = "n", pch = symb_def[BIC_burst[p_x2_burst > 0.05]], col =col_def[ BIC_burst[p_x2_burst > 0.05] ], xlab = "True p of NB", ylab = "True r of NB", cex = 1.2, main = "Data generated by bursting model",
     lwd= def_lwd[BIC_burst[p_x2_burst > 0.05]], ylim = c(0,60))
legend("topright", legend = c("Pois", "PB", "NB", "DEL", "PIG"), col = col_def, pch = symb_def, bty ="n", cex = 1.2, lwd = def_lwd, lty = 0)
dev.off()

########################################################################################################################################
# IG Basic Burst Modell Fits: Zusammenfassung

BIC_IGbasicburst_pois<- c(0,1000)
BIC_IGbasicburst_nb<- c(0,1000)
BIC_IGbasicburst_pb<- c(0,1000)
BIC_IGbasicburst_pig<- c(0,1000)
BIC_IGbasicburst_del<- c(0,1000)

for(i in 1:1000){
    
    # fitted NB parameter
    load(file=paste0("FitData/IGBasicBurst/IGbasicburst_",i,".rda"))
    #f_param_nb <- f_nb$par
    
    BIC_IGbasicburst_pois[i] <- f_pois$BIC
    BIC_IGbasicburst_nb[i] <- f_nb$BIC
    try(BIC_IGbasicburst_pb[i] <- f_pb$BIC, silent = TRUE)
    BIC_IGbasicburst_pig[i] <- f_pig$BIC
    BIC_IGbasicburst_del[i] <- f_del$BIC
}

# GOF
BIC_IGbasicburst_help <- matrix(rep(0,1000), ncol = 1)
rownames( BIC_IGbasicburst_help) <- 1:1000
p_x2_IGbasicburst <- rep(0,1000)

for(i in 1:1000){
    load(file=paste0("GOFData/IGBasicBurst/p_gof_IGbasicburst_",i,".rda"))
    BIC_IGbasicburst_help[i,] <- minBIC
    rownames( BIC_IGbasicburst_help)[i] <- names(minBIC)
    p_x2_IGbasicburst[i] <- p_x2$p.value
}



BIC_IGbasicburst <- rownames( BIC_IGbasicburst_help)

# true parameter
t_param_IGbasicburst <- c(Parameter_IGBasic_Burst$burst[i], Parameter_IGBasic_Burst$mu[i], Parameter_IGBasic_Burst$degr[i])

# derived "true" parameter of the PIG
Parameter_PIG_mu <- 2*Parameter_IGBasic_Burst$mu/Parameter_IGBasic_Burst$degr
Parameter_PIG_lambda <-  4*Parameter_IGBasic_Burst$burst*Parameter_IGBasic_Burst$mu/(Parameter_IGBasic_Burst$degr)^2




# Filterung mit GOF
pdf("GOFData/IGBasicBurst/Analyse_IGbasicBurst_2.pdf", width = 10, height = 4)
plot(Parameter_PIG_mu[p_x2_IGbasicburst > 0.05], Parameter_PIG_lambda[p_x2_IGbasicburst > 0.05], type = "p", bty = "n", pch = symb_def[BIC_IGbasicburst[p_x2_IGbasicburst > 0.05]], col = col_def[BIC_IGbasicburst[p_x2_IGbasicburst > 0.05] ], xlab = bquote(paste("True ", lambda ," of PIG")), cex = 1.2, ylab = bquote(paste("True ", mu, " of PIG")), main = "Data generated by IG basic bursting model", lwd= def_lwd[BIC_IGbasicburst[p_x2_IGbasicburst > 0.05]], xlim = c(0,500), ylim = c(0,100000))
#legend("topright", legend = c("Pois", "PB", "NB", "DEL", "PIG"), col = col_def, pch = symb_def, bty ="n", cex = 1.2, lwd = def_lwd, lty = 0)
dev.off()

########################################################################################################################################
# Combined basic and burst Modell Fits: Zusammenfassung

BIC_basicburst_pois<- c(0,1000)
BIC_basicburst_nb<- c(0,1000)
BIC_basicburst_pb<- c(0,1000)
BIC_basicburst_del<- c(0,1000)
BIC_basicburst_pig<- c(0,1000)

for(i in 1:1000){
    
    # fitted NB parameter
    load(file=paste0("FitData/BasicBurst/basicburst_",i,".rda"))
    #f_param_pb <- f_pb$par
    
    BIC_basicburst_pois[i] <- f_pois$BIC
    BIC_basicburst_nb[i] <- f_nb$BIC
    BIC_basicburst_pb[i] <- f_pb$BIC
    BIC_basicburst_pig[i] <- f_pig$BIC
    BIC_basicburst_del[i] <- f_del$BIC

}

# GOF
BIC_basicburst_help <- matrix(rep(0,1000), ncol = 1)
rownames( BIC_basicburst_help) <- 1:1000
p_x2_basicburst <- rep(0,1000)

for(i in 1:1000){
    load(file=paste0("GOFData/BasicBurst/p_gof_basicburst_",i,".rda"))
    BIC_basicburst_help[i,] <- minBIC
    rownames( BIC_basicburst_help)[i] <- names(minBIC)
    p_x2_basicburst[i] <- p_x2$p.value
}



BIC_basicburst <- rownames( BIC_basicburst_help)

# true parameter
t_param_basicburst <-  c(Parameter_Basic_Burst$trans[i], Parameter_Basic_Burst$burst[i], Parameter_Basic_Burst$size[i], Parameter_Basic_Burst$degr[i])

# derived "true" parameter of the DEL
Parameter_DEL_mu <- (Parameter_Basic_Burst$tran + Parameter_Basic_Burst$burst * Parameter_Basic_Burst$size) / Parameter_Basic_Burst$degr
Parameter_DEL_sigma <- Parameter_Basic_Burst$degr / Parameter_Basic_Burst$burst
Parameter_DEL_nu <- Parameter_Basic_Burst$tran/(Parameter_Basic_Burst$tran + Parameter_Basic_Burst$burst * Parameter_Basic_Burst$size)



# Filterung mit GOF
pdf("GOFData/BasicBurst/Analyse_basicburst_2_1.pdf", width = 10, height = 4)
plot(Parameter_DEL_mu[p_x2_basicburst > 0.05], Parameter_DEL_sigma[p_x2_basicburst > 0.05],xlim = c(0,500), bty = "n", type = "p", pch = symb_def[BIC_basicburst[p_x2_basicburst > 0.05]], col = col_def[BIC_basicburst[p_x2_basicburst > 0.05] ], xlab = bquote(paste("True ", mu ," of DEL")) , cex = 1.2, ylab = bquote(paste("True ", sigma ," of DEL")), main = "Data generated by combined basic and bursting model",
     lwd= def_lwd[BIC_basicburst[p_x2_basicburst > 0.05]])
#legend("topright", legend = c("Pois", "PB", "NB", "DEL", "PIG"), col = col_def, pch = symb_def, bty ="n", cex = 1.2, lwd = def_lwd, lty = 0)
dev.off()

pdf("GOFData/BasicBurst/Analyse_basicburst_2_2.pdf", width = 10, height = 4)
plot(Parameter_DEL_nu[p_x2_basicburst > 0.05], Parameter_DEL_sigma[p_x2_basicburst > 0.05], bty = "n", type = "p", pch = symb_def[BIC_basicburst[p_x2_basicburst > 0.05]], col = col_def[BIC_basicburst[p_x2_basicburst > 0.05]], xlab = bquote(paste("True ", nu ," of DEL")), cex = 1.2, ylab =  bquote(paste("True ", sigma ," of DEL")), main = "Data generated by combined basic and bursting model", 
     lwd= def_lwd[BIC_basicburst[p_x2_basicburst > 0.05]])
#legend("topright", legend = c("Pois", "PB", "NB", "DEL", "PIG"), col = col_def, pch = symb_def, bty ="n", cex = 1.2, lwd = def_lwd, lty = 0)
dev.off()

pdf("GOFData/BasicBurst/Analyse_basicburst_2_3.pdf", width = 10, height = 4)
plot(Parameter_DEL_mu[p_x2_basicburst > 0.05], Parameter_DEL_nu[p_x2_basicburst > 0.05],xlim = c(0,500), bty = "n", type = "p", pch = symb_def[BIC_basicburst[p_x2_basicburst > 0.05]], col = col_def[BIC_basicburst[p_x2_basicburst > 0.05] ], xlab =  bquote(paste("True ", mu ," of DEL")), cex = 1.2, ylab =bquote(paste("True ", nu ," of DEL")), main = "Data generated by combined basic and bursting model",
     lwd= def_lwd[BIC_basicburst[p_x2_basicburst > 0.05]])
#legend("topright",legend = c("Pois", "PB", "NB", "DEL", "PIG"), col = col_def, pch = symb_def, bty ="n", cex = 1.2, lwd = def_lwd, lty = 0)
dev.off()


########################################################################################################################################
# Stacked Baroplots Overview ALL

h <- matrix(c( table(BIC_IGbasicburst)["pois"], 0,  table(BIC_IGbasicburst)["nb"],  table(BIC_IGbasicburst)["del"],  table(BIC_IGbasicburst)["pig"],
               table(BIC_basicburst)["pois"], 0, table(BIC_basicburst)["nb"],  table(BIC_basicburst)["del"],  table(BIC_basicburst)["pig"],
               0, table(BIC_burst)["pb"], table(BIC_burst)["nb"],table(BIC_burst)["del"],  table(BIC_burst)["pig"] ,
               0, table(BIC_switch)["pb"], table(BIC_switch)["nb"] ,0, table(BIC_switch)["pig"],
               table(BIC_basic)["pois"],0,  table(BIC_basic)["nb"],0,  table(BIC_basic)["pig"]),
               5,5, byrow=FALSE)
H <- apply(h, 2L, cumsum)
H <- H - h / 2


# Filterung mit GOF
pdf("GOFData/Overview_Barplot_2.pdf", width = 10, height = 4)
h <- matrix(c(table(BIC_IGbasicburst[p_x2_IGbasicburst > 0.05])["pois"], 0,  table(BIC_IGbasicburst[p_x2_IGbasicburst > 0.05])["nb"],  table(BIC_IGbasicburst[p_x2_IGbasicburst > 0.05])["del"],  table(BIC_IGbasicburst[p_x2_IGbasicburst > 0.05])["pig"],
                 table(BIC_basicburst[p_x2_basicburst > 0.05])["pois"], 0, table(BIC_basicburst[p_x2_basicburst > 0.05])["nb"],  table(BIC_basicburst[p_x2_basicburst > 0.05])["del"],  table(BIC_basicburst[p_x2_basicburst > 0.05])["pig"],
                 0, table(BIC_burst[p_x2_burst > 0.05])["pb"], table(BIC_burst[p_x2_burst > 0.05])["nb"],table(BIC_burst[p_x2_burst > 0.05])["del"],  table(BIC_burst[p_x2_burst > 0.05])["pig"] ,
                 0, table(BIC_switch[p_x2_switch > 0.05])["pb"], table(BIC_switch[p_x2_switch > 0.05])["nb"] ,0, table(BIC_switch[p_x2_switch > 0.05])["pig"],
                 table(BIC_basic[p_x2_basic > 0.05])["pois"],0,  table(BIC_basic[p_x2_basic > 0.05])["nb"],0,  table(BIC_basic[p_x2_basic > 0.05])["pig"]),
     5,5, byrow=FALSE)

H <- apply(h, 2L, cumsum)
H <- H - h / 2
y <- barplot(h,xlim=c(0,1000),  col =col_def, horiz = TRUE, legend.text = c("Pois", "PB", "NB", "DEL", "PIG"), args.legend=list("topright", bty ="n"), names.arg =c("IG basic 
bursting
model", "basic 
bursting
model", "switching
model", "bursting
model","basic
model"), main = "Best model fits via BIC (after GOF)", las = 1)
text((H[1,5]), rep(y[5], 1), labels = paste0(h[1,5]), col = "white")
text((H[3,5]-5), rep(y[5], 1), labels = paste0(h[3,5]), col = "white")
text((H[5,5])+10, rep(y[5], 1), labels = paste0(h[5,5]))
text((H[2,4]), rep(y[4], 1), labels = paste0(h[2,4]))
text((H[3,4])-10, rep(y[4], 1), labels = paste0(h[3,4]), col ="white")
text((H[5,4])+20, rep(y[4], 1), labels = paste0(h[5,4]))
text((H[2,3])+15, rep(y[3], 1), labels = paste0(h[2,3]), col = "white")
text((H[c(3),3]), rep(y[3], 1), labels = paste0(h[c(3),3]), col = "white")
text((H[c(4),3]-10), rep(y[3], 1), labels = paste0(h[c(4),3]), col = "white")
text((H[c(5),3]+30), rep(y[3], 1), labels = paste0(h[c(5),3]))
text((H[c(1,3,5),2]), rep(y[2], 3), labels = paste0(h[c(1,3,5),2]), col = "white")
text((H[c(4),2]), rep(y[2], 1), labels = paste0(h[c(4),2]))
text((H[c(1,3,5),1]), rep(y[1], 3), labels = paste0(h[c(1,3,5),1]), col = "white")
text((H[c(4),1]), rep(y[1], 1), labels = paste0(h[c(4),1]))

dev.off()

