# Lade Parameter der Simulation


load("Parameter_BasicSwitchBurst.rda")

########################################################################################################################################
# Basic Modell Fits: Zusammenfassung


BIC_basic_pois<- c(NA,1000)
BIC_basic_nb<- c(NA,1000)
BIC_basic_pb<- c(NA,1000)

for(i in 1:1000){
    # fitted NB parameter
    load(file=paste0("basic_",i,".rda"))
    #f_param_pb <- f_pb$par

    BIC_basic_pois[i] <- f_pois$BIC
    BIC_basic_nb[i] <- f_nb$BIC
    BIC_basic_pb[i] <- f_pb$BIC
}


# GOF
BIC_basic <- rep(NA,1000)
p_x2_basic <- rep(NA,1000)

for(i in (1:1000)){
    load(file=paste0("p_gof_basic_",i,".rda"))
    BIC_basic[i] <- minBIC
    p_x2_basic[i] <- p_x2$p.value
}


# true parameter
t_param_basic <-  c(Parameter_Basic$trans[i], Parameter_Basic$degr[i])

# derived "true" parameter of the PB
Parameter_Pois <- Parameter_Basic$trans/Parameter_Basic$degr



# Filterung mit GOF
pdf("Analyse_Basic_2.pdf", width = 10, height = 4)
plot(Parameter_Pois[p_x2_basic[!is.na(p_x2_basic)] > 0.05], rep(0,length(Parameter_Pois[p_x2_basic[!is.na(p_x2_basic)] > 0.05])),bty ="n", yaxt = "n",ylim = c(-1,1),type = "p", pch = BIC_basic[p_x2_basic[!is.na(p_x2_basic)] > 0.05], col = BIC_basic[p_x2_basic[!is.na(p_x2_basic)] > 0.05] + 1, xlab = bquote(paste("Parameter of Poisson distribution: ",lambda)) ,ylab ="", main = "Data generated by basic model: Overview fitted models via highest BIC")
legend("topright", legend = c("Pois", "NB", "PB"), col = c(2,3,4), pch = c(1,2,3), bty ="n")
dev.off()



########################################################################################################################################
# Switch Modell Fits: Zusammenfassung

BIC_switch_pois<- c(0,1000)
BIC_switch_nb<- c(0,1000)
BIC_switch_pb<- c(0,1000)

for(i in 1:1000){

    # fitted NB parameter
    load(file=paste0("switch_",i,".rda"))
    #f_param_pb <- f_pb$par

    BIC_switch_pois[i] <- f_pois$BIC
    BIC_switch_nb[i] <- f_nb$BIC
    BIC_switch_pb[i] <- f_pb$BIC
}

# GOF
BIC_switch <- rep(0,1000)
p_x2_switch <- rep(0,1000)

for(i in 1:1000){
    load(file=paste0("p_gof_switch_",i,".rda"))
    BIC_switch[i] <- minBIC
    p_x2_switch[i] <- p_x2$p.value
}


# true parameter
t_param_switch <-  c(Parameter_Switch$act[i], Parameter_Switch$deact[i], Parameter_Switch$on[i], Parameter_Switch$degr[i])

# derived "true" parameter of the PB
Parameter_PB_alpha <- Parameter_Switch$act/Parameter_Switch$degr
Parameter_PB_beta <- Parameter_Switch$deact/Parameter_Switch$degr
Parameter_PB_c <- Parameter_Switch$on/Parameter_Switch$degr



# Filterung mit GOF
pdf("Analyse_Switch_2_1.pdf", width = 10, height = 4)
plot(Parameter_PB_alpha[p_x2_switch > 0.05], Parameter_PB_beta[p_x2_switch > 0.05],xlim = c(0,70), bty = "n", type = "p", pch = BIC_switch[p_x2_switch > 0.05], col = BIC_switch[p_x2_switch > 0.05] + 1, xlab = bquote(paste("1st Parameter of Poisson-beta: ",alpha)) , ylab = bquote(paste("2nd Parameter of Poisson-beta: ",beta)), main = "Data generated by switching model:
Overview fitted models via highest BIC")
legend("topright", legend = c("Pois", "NB", "PB"), col = c(2,3,4), pch = c(1,2,3), bty ="n")
dev.off()

pdf("Analyse_Switch_2_2.pdf", width = 10, height = 4)
plot(Parameter_PB_c[p_x2_switch > 0.05], Parameter_PB_beta[p_x2_switch > 0.05],xlim = c(0,2800), bty = "n", type = "p", pch = BIC_switch[p_x2_switch > 0.05], col = BIC_switch[p_x2_switch > 0.05] + 1, xlab = bquote(paste("3rd Parameter of Poisson-beta: c")), ylab =  bquote(paste("2nd Parameter of Poisson-beta: ",beta)), main = "Data generated by switching model:
Overview fitted models via highest BIC")
legend("topright", legend = c("Pois", "NB", "PB"), col = c(2,3,4), pch = c(1,2,3), bty ="n")
dev.off()

pdf("Analyse_Switch_2_3.pdf", width = 10, height = 4)
plot(Parameter_PB_alpha[p_x2_switch > 0.05], Parameter_PB_c[p_x2_switch > 0.05],xlim = c(0,70), bty = "n", type = "p", pch = BIC_switch[p_x2_switch > 0.05], col = BIC_switch[p_x2_switch > 0.05] + 1, xlab =  bquote(paste("1st Parameter of Poisson-beta: ",alpha)), ylab =bquote(paste("3rd Parameter of Poisson-beta: c")), main = "Data generated by switching model:
Overview fitted models via highest BIC")
legend("topright", legend = c("Pois", "NB", "PB"), col = c(2,3,4), pch = c(1,2,3), bty ="n")
dev.off()


########################################################################################################################################
# Burst Modell Fits: Zusammenfassung

BIC_burst_pois<- c(0,1000)
BIC_burst_nb<- c(0,1000)
BIC_burst_pb<- c(0,1000)

for(i in 1:1000){

    # fitted NB parameter
    load(file=paste0("burst_",i,".rda"))
    #f_param_nb <- f_nb$par

    BIC_burst_pois[i] <- f_pois$BIC
    BIC_burst_nb[i] <- f_nb$BIC
    BIC_burst_pb[i] <- f_pb$BIC
}

# GOF
BIC_burst <- rep(0,1000)
p_x2_burst <- rep(0,1000)

for(i in 1:1000){
    load(file=paste0("p_gof_burst_",i,".rda"))
    BIC_burst[i] <- minBIC
    p_x2_burst[i] <- p_x2$p.value
}


# true parameter
t_param_burst <- c(Parameter_Burst$burst[i], Parameter_Burst$size[i], Parameter_Burst$degr[i])

# derived "true" parameter of the NB
Parameter_NB_r <- Parameter_Burst$burst/Parameter_Burst$degr
Parameter_NB_p <-  1/(Parameter_Burst$size+1)




# Filterung mit GOF
pdf("Analyse_Burst_2.pdf", width = 10, height = 4)
plot(Parameter_NB_p[p_x2_burst > 0.05], Parameter_NB_r[p_x2_burst > 0.05], type = "p", bty = "n", pch = BIC_burst[p_x2_burst > 0.05], col = BIC_burst[p_x2_burst > 0.05] + 1, xlab = "2nd parameter of negative binomial: p", ylab = "1st  parameter of negative binomial: r", main = "Data generated by bursting model:
Overview fitted models via highest BIC")
legend("topright", legend = c("Pois", "NB", "PB"), col = c(2,3,4), pch = c(1,2,3), bty ="n")
dev.off()


########################################################################################################################################
# Stacked Baroplots Overview ALL
h <- matrix(c(0,table(BIC_switch),0,table(BIC_burst), table(BIC_basic[!is.na(BIC_basic)] ),0), 3,3, byrow=FALSE)
H <- apply(h, 2L, cumsum)
H <- H - h / 2


# Filterung mit GOF
pdf("Overview_Barplot_2.pdf", width = 10, height = 4)
h <- matrix(c(0,table(BIC_switch[p_x2_switch > 0.05]),0,table(BIC_burst[p_x2_burst > 0.05]), table(BIC_basic[p_x2_basic[!is.na(p_x2_basic)] > 0.05]),0,0), 3,3, byrow=FALSE)
H <- apply(h, 2L, cumsum)
H <- H - h / 2
y <- barplot(h,xlim=c(0,1000),  col =c(2,3,4), horiz = TRUE, legend.text = c("Pois", "NB", "PB"), args.legend=list("topright", bty ="n"), names.arg =c("switching
model", "bursting
model","basic
model"), main = "Overview best fits of simulated data by the three modells
after GOF", las = 1)
text((H[1,3]), rep(y[3], 2), labels = paste0(h[1,3]))
text(H[2:3,2], rep(y[2], 2), labels = paste0(h[2:3,2]), col = c(1,"white"))
text(H[2:3,1], rep(y[1], 2), labels = paste0(h[2:3,1]), col = c(1,"white"))
dev.off()

